# -*- coding: utf-8 -*-
"""app_state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10i_LRlDeLl6bFLAMJlTsJUZOZKLUl5zS
"""

"""
app_state.py
------------
Shared mutable state between the Colab setup notebook and the FastAPI app.

The Colab notebook loads heavy models (vectorstore, LLM, Whisper) once,
then injects them here. FastAPI's main.py imports from this module so it
always uses the already-loaded instances — no double loading.
"""

vectorstore   = None   # FAISS vectorstore (set in Cell 10 of colab_setup.py)
llm_pipeline  = None   # HuggingFace text-generation pipeline
whisper_model = None   # Whisper model instance